SELECT c.CAR_ID, c.CAR_TYPE, 
        ROUND(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30, 0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR c
    # 대여 기록 중에 11/1 ~ 11/30 기록이 있으면 배제해야 하는데 어떻게 하지? -> 아래 답
    JOIN (SELECT p.CAR_TYPE, p.DURATION_TYPE, p.DISCOUNT_RATE 
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
          WHERE p.DURATION_TYPE = '30일 이상') p
    ON c.CAR_TYPE = p.CAR_TYPE 
    
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
    AND ROUND(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30, 0) >= 500000
    AND ROUND(c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 * 30, 0) < 2000000
    AND c.CAR_ID NOT IN (SELECT c2.CAR_ID
      FROM CAR_RENTAL_COMPANY_CAR c2
            JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h2
            ON c2.CAR_ID = h2.CAR_ID
      WHERE (h2.START_DATE <= '2022-11-30') AND (h2.END_DATE >= '2022-11-01')
     ) # 빌릴 수 없는 CAR_ID를 WHERE (..) NOT IN (..) 으로 제외
    
    
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC