SELECT A.ROUTE ROUTE,
        CONCAT(ROUND(SUM(A.D_BETWEEN_DIST), 1), 'km') TOTAL_DISTANCE,
        CONCAT(ROUND(AVG(A.D_BETWEEN_DIST), 2), 'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE A
GROUP BY A.ROUTE
ORDER BY ROUND(SUM(A.D_BETWEEN_DIST), 1) DESC