SELECT A.CAR_TYPE, 
        COUNT(*) CARS
FROM CAR_RENTAL_COMPANY_CAR A
WHERE A.OPTIONS LIKE '%통풍시트%' 
        OR A.OPTIONS LIKE '%열선시트%' 
        OR A.OPTIONS LIKE '%가죽시트%'
GROUP BY A.CAR_TYPE 
ORDER BY A.CAR_TYPE