WITH TotalUsers AS (
    SELECT
        COUNT(USER_ID) AS total_users
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
SELECT 
    DATE_FORMAT(o.SALES_DATE, '%Y') AS YEAR,
    CONVERT(DATE_FORMAT(o.SALES_DATE, '%m'), DECIMAL) AS MONTH,
    COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT u.USER_ID) / (SELECT total_users FROM TotalUsers),
        1
    ) AS PURCHASED_RATIO
FROM USER_INFO u
    JOIN ONLINE_SALE o
    ON u.USER_ID = o.USER_ID
WHERE u.JOINED LIKE '2021%'
GROUP BY DATE_FORMAT(o.SALES_DATE, '%Y-%m')
ORDER BY YEAR, MONTH