SELECT  YEAR(B.SALES_DATE) YEAR,
        MONTH(B.SALES_DATE) MONTH,
        COUNT(DISTINCT A.USER_ID) PURCHASED_USERS,
        ROUND(COUNT(DISTINCT A.USER_ID) / C.ALL_USER, 1) PUCHASED_RATIO
FROM USER_INFO A
    JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
    CROSS JOIN (SELECT COUNT(*) AS ALL_USER
                FROM USER_INFO U
                WHERE YEAR(U.JOINED) = 2021 ) C
WHERE YEAR(A.JOINED) = 2021 
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)