SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT) * p.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT p
    JOIN FOOD_ORDER o
    ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m-%d') BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC
