SELECT B.WRITER_ID WRITER_ID,
        C.NICKNAME NICKNAME,
        B.TOTAL_SALES TOTAL_SALES
FROM (SELECT A.WRITER_ID WRITER_ID,
        SUM(A.PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD A
    WHERE A.STATUS = 'DONE'
    GROUP BY A.WRITER_ID
    ) B
    JOIN USED_GOODS_USER C
    ON B.WRITER_ID = C.USER_ID
WHERE B.TOTAL_SALES >= 700000
ORDER BY 3