SELECT a.ANIMAL_ID, a.NAME
FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b
    ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE b.ANIMAL_ID IS NOT NULL 
        AND a.ANIMAL_ID IS NOT NULL
        AND a.DATETIME > b.DATETIME 
ORDER BY a.DATETIME