SELECT MONTH(B.START_DATE) MONTH,
        B.CAR_ID CAR_ID,
        COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE B.CAR_ID
    IN (SELECT A.CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
            WHERE YEAR(A.START_DATE) = 2022 AND MONTH(A.START_DATE) >= 8 AND MONTH(A.START_DATE) <= 10
            GROUP BY A.CAR_ID
            HAVING COUNT(*) >= 5)
        AND YEAR(B.START_DATE) = 2022 AND MONTH(B.START_DATE) >= 8 AND MONTH(B.START_DATE) <= 10
GROUP BY MONTH(B.START_DATE), B.CAR_ID
ORDER BY 1, 2 DESC