SELECT COUNT(*) FISH_COUNT,
        MONTH(DATE_FORMAT(A.TIME, '%Y-%m-%d')) MONTH
FROM FISH_INFO A
# WHERE FISH_COUNT IS NOT 0
GROUP BY MONTH(DATE_FORMAT(A.TIME, '%Y-%m-%d'))
ORDER BY MONTH(DATE_FORMAT(A.TIME, '%Y-%m-%d'))