SELECT SUM(G.SCORE) SCORE,
        G.EMP_NO EMP_NO,
        E.EMP_NAME EMP_NAME,
        E.POSITION POSITION,
        E.EMAIL EMAIL
FROM HR_EMPLOYEES E
    JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SUM(G.SCORE) DESC
LIMIT 1