SELECT A.DEPT_ID, A.DEPT_NAME_EN, 
        ROUND(SUM(SAL) / COUNT(*), 0) AVG_SAL
FROM HR_DEPARTMENT A
    JOIN HR_EMPLOYEES B
    ON A.DEPT_ID = B.DEPT_ID
# WHERE
GROUP BY A.DEPT_ID
# HAVING
ORDER BY 3 DESC
# LIMIT