SELECT B.CATEGORY CATEGORY,
        SUM(A.SALES) TOTAL_SALES
FROM BOOK_SALES A
    JOIN BOOK B
    ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR(A.SALES_DATE) = 2022 AND MONTH(A.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY 1